import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Satoshi = localFont({
  src: "../../public/fonts/Satoshi-Variable.ttf",
  variable: "--font-satoshi",
  display: "swap",
});

const Nohemi = localFont({
  src: [
    {
      path: "../../public/fonts/Nohemi-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Nohemi-Bold.otf",
      weight: "700",
      style: "normal",
    }
  ],
  variable: "--font-nohemi",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Bantugi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${Satoshi.variable} ${Nohemi.variable} scroll-smooth`}>
      <body
        className="font-satoshi antialiased"
      >
        {children}
      </body>
    </html>
  );
}
