import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Satoshi = localFont({
  src: "../../public/fonts/Satoshi-Variable.ttf"
});

const Nohemi = localFont({
  src: [
    {
      path: "../../public/fonts/Nohemi-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Nohemi-Bold.otf",
      weight: "700",
      style: "normal",
    }
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Satoshi.className} ${Nohemi.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
