# Generated by Django 4.2.8 on 2025-05-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0011_alter_otptoken_otp_code_alter_otptoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='supabase_uid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
